- id: commitlint
  name: commitlint
  description: Commitlint hook
  language: node
  entry: commitlint --config commitlint.config.js --edit
  pass_filenames: false
  always_run: true
  stages: [commit-msg]
